plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = "${mod_version}"
group = "${mod_group_id}"

repositories {
    mavenCentral()
    mavenLocal()

    //Modrinth 仓库 (官方推荐写法)
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"

            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
    maven { url = "https://maven.createmod.net" }
}
base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
}

neoForge {
    version = project.neo_version

    parchment {
        // Optional: better parameter names in IDE
        // mappingsVersion = "2024.11.17"
        // minecraftVersion = "1.21.1"
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
    }
}

dependencies {
    // ==========================================
    // 彻底告别本地 libs，全部采用远程强类型 Maven 拉取！
    // ==========================================

    // --- Ponder ---
    compileOnly "net.createmod.ponder:ponder-neoforge:1.0.81+mc1.21.1"
    runtimeOnly "net.createmod.ponder:ponder-neoforge:1.0.81+mc1.21.1"

    //CRN 和 DragonLib
    compileOnly "maven.modrinth:create-railways-navigator:1.21.1-beta-0.9.1-C6"
    runtimeOnly "maven.modrinth:create-railways-navigator:1.21.1-beta-0.9.1-C6"
    compileOnly "maven.modrinth:dragonlib:M6CMBAur"
    runtimeOnly "maven.modrinth:dragonlib:M6CMBAur"
    compileOnly "maven.modrinth:create:mc1.21.1-6.0.9"
    runtimeOnly "maven.modrinth:create:mc1.21.1-6.0.9"

}
// Mixin configuration
configurations.configureEach {
    resolutionStrategy.force "net.sf.jopt-simple:jopt-simple:5.0.4"
}

processResources {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            java_version           : java_version,
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'   : mod_id,
                'Specification-Vendor'  : mod_authors,
                'Specification-Version' : '1',
                'Implementation-Title'  : mod_name,
                'Implementation-Version': mod_version,
                'Implementation-Vendor' : mod_authors,
        ])
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}