# Mod Info
mod_id=crndisplaynext
mod_name=CRN Display Extended
mod_version=1.0.0
mod_group_id=com.hybrizat.crndisplaynext
mod_authors=Hybrizat
mod_description=Addon for Create: Train Navigator adding advanced display features.

# Minecraft & NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.77
neo_version_range=[21.1,)

# Dependencies versions
# Check https://maven.createmod.net for latest Create version
create_version=6.0.9
# Check CRN releases on GitHub/Modrinth for latest version
crn_version=0.9.0

# Java
java_version=21

# Gradle
org.gradle.jvmargs=-Xmx4g
org.gradle.daemon=true
org.gradle.parallel=true
